# ./.graphqlrc.yml
schema: "../dist/page.graphql"
extensions:
  codegen:
    generates:
      ../dist/page.fragments.graphql:
        plugins:
          - "@kickstartds/graphql-cli-generate-fragments"
