# ./.graphqlconfig.yml
projects:
  kickstartDS:
    schemaPath: ../dist/page.graphql
    extensions:
      generate-fragments:
        output: ../dist/page.fragments.graphql
        generator: graphql
